name: 'Validate Cedar Policies'
description:
  'A GitHub Action to validate Cedar policies against a Cedar schema.'
author: 'Common Fate'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  schema-file:
    description:
      'The path to the Cedar schema file to use for validation. If a glob is
      specified, the first file matching the glob will be used.'
    required: true
    default: '**/*.cedarschema.json'
  ignore-confusable-identifier-warning:
    description:
      'Ignore the confusable identifier warning, to prevent "/" characters in
      entity IDs from triggering warnings. Defaults to true. When
      https://github.com/cedar-policy/cedar/issues/621 is resolved, the default
      will be updated to false.'
    required: true
    default: 'true'
  fail-on-warnings:
    description: 'Set the action status to fail if any warnings are present.'
    required: true
    default: 'true'

runs:
  using: node20
  main: dist/index.js
