name: 'Validate Cedar Policies'
description:
  'A GitHub Action to validate Cedar policies against a Cedar schema.'
author: 'Common Fate'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  schema-file:
    description:
      'The path to the Cedar schema file to use for validation. If a glob is
      specified, the first file matching the glob will be used.'
    required: true
    default: '**/*.cedarschema.json'

runs:
  using: node20
  main: dist/index.js
